config/database.js, config/env/development/database.js, package-lock.json, package.json
This removes the need to run postgres with docker
=> feat(chungthuang): Use sqlite for local development

src/api/opportunity/content-types/opportunity/schema.json, src/api/opportunity/controllers/opportunity.js, src/api/opportunity/documentation/1.0.0/opportunity.json, src/api/opportunity/routes/opportunity.js, src/api/opportunity/services/opportunity.js, src/api/project/content-types/project/schema.json, src/components/positions/expectations.json
Migrate https://github.com/dev-launchers/strapi/tree/main/api/opportunities.
Resolves: #40
=> feat(chungthuang): Migrate opportunity collection

src/extensions/users-permissions/content-types/user/schema.json
The completeOnboarding variable will keep track of whether the user has completed the onboarding process.
=> Added completedOnboarding variable to user model

src/extensions/documentation/documentation/1.0.0/full_documentation.json, src/extensions/users-permissions/server/middlewares/jwt.js
=> fix(cthuang): Redirect user to signup or user profile page after sign in

config/plugins.js, production/kustomization.yaml, src/api/project/controllers/project.js, staging/kustomization.yaml, workload/deployment.yaml
=> Release 1.4.2

src/api/profile/content-types/profile/lifecycles.js
This is my first pull request here, any feedback would be much appreciated. This is to fix the issue here: https://github.com/dev-launchers/strapiv4/issues/120
=> Fixed issue with profile picture URL update

config/plugins.js, package-lock.json, package.json
Example response from `/api/metrics`:
```
number_of_open_connections 0
http_request_duration_s_bucket{le="0.05",method="POST",path="/admin/login",status="200"} 0
http_request_duration_s_bucket{le="0.1",method="POST",path="/admin/login",status="200"} 0
http_request_duration_s_bucket{le="0.2",method="POST",path="/admin/login",status="200"} 1
http_request_duration_s_bucket{le="0.3",method="POST",path="/admin/login",status="200"} 1
http_request_duration_s_bucket{le="0.4",method="POST",path="/admin/login",status="200"} 1
http_request_duration_s_bucket{le="0.5",method="POST",path="/admin/login",status="200"} 1
http_request_duration_s_bucket{le="1",method="POST",path="/admin/login",status="200"} 1
http_request_duration_s_bucket{le="2",method="POST",path="/admin/login",status="200"} 1 …
```
=> feat(chungthuang): Produce prometheus metrics for API responses by status code

.env.example, .gitignore, Dockerfile.dev, README.md, config/env/development/plugins.js, config/middlewares.js, docs/local-setup.md, init/cleanup.js, init/config.js, init/permissions/authenticated.js, init/permissions/public.js, init/set-permissions.js, init/setup.js, package.json, src/extensions/users-permissions/server/middlewares/jwt.js
=> feat(dev-env): Improvements, Fixes, Documentation for local environment 

.github/workflows/playwright.yaml, .gitignore, .nycrc, README.md, config/env/test/database.js, init/cleanup.js, init/common.js, init/config.js, init/set-permissions.js, init/setup.js, package-lock.json, package.json, playwright.config.ts, src/api/comment/content-types/comment/lifecycles.js, src/api/idea-card/content-types/idea-card/lifecycles.js, tests/global-setup.ts, tests/global-teardown.ts, tests/idea-space.spec.ts, tests/interest.spec.ts, tests/notification.spec.ts, tests/project.spec.ts, tests/user.spec.ts, tests/utils.ts
Partially covers #178 
@chungthuang @oriyomibadmus @nikita-pardeshi-github @tiagopazhs Please review.
In the following phase, I will update Actions and remove existing integrated tests and add more tests.
Please let me know if you need more details on how write tests.
=> Experiment with Playwright Test Framework 

.gitignore, config/migrations.js, init/common.js, src/api/comment/content-types/comment/lifecycles.js, src/api/comment/content-types/comment/schema.json, src/extensions/users-permissions/content-types/user/schema.json, src/index.js, src/migrators/comments.js, src/migrators/index.js, tests/global-teardown.ts, tests/idea-space.spec.ts, tests/interest.spec.ts, tests/utils.ts, types/generated/contentTypes.d.ts
=> feat(comments): Backward compatibility and migration framework.

src/api/applicant/content-types/applicant/schema.json, types/generated/contentTypes.d.ts
Added a new column named yearsExperience to the Applicant model.
=> feat:Add yearsExperience to Applicant

init/common.js, init/config.js, tests/project.spec.ts, tests/user.spec.ts
Hi @chungthuang, I have incorporated all review comments here.
=> feat: 191 project api test coverage

init/permissions/authenticated.js, src/api/notification/routes/custom-notification.js, src/api/notification/routes/notification.js, tests/notification.spec.ts
This should only be used to update a notification readDataeTime
=> feat(notifications): Expose a PUT endpoint to update notification

.github/workflows/publish-types.yaml
update node version from 14 to 20
=> uptade node version

.github/workflows/publish-types.yaml, package.json
I created a script "install-all" pointing for the path and right now we have a package.json in the type folder
=> package.json in the type folder

.github/workflows/publish-types.yaml
I made some changes in the code workflow/publish-types for solving some errors log @chungthuang
=> Testing publish workflow

init/config.js, src/extensions/users-permissions/content-types/user/schema.json, tests/user.spec.ts, types/generated/contentTypes.d.ts
This is part of https://github.com/dev-launchers/dev-launchers-platform/issues/1930.
=> feat(user): Add professionalRole field to the user collection

src/api/comment/content-types/comment/lifecycles.js, src/api/idea-card/content-types/idea-card/lifecycles.js, tests/event.spec.ts, tests/notification.spec.ts
- changed event content  field when event is created in both commnet and idea lifecycle
- for comments the event content will be the comment text
- for idea it will be the idea description
=> changed event content field

src/api/comment/content-types/comment/lifecycles.js, src/api/event/content-types/event/lifecycles.js, tests/event.spec.ts
- user that comments is subscribed to the idea card not the comment
- when user comments all who are subscribed to the idea card get a notification
=> fix(notification) : user comment subscription for notification

src/extensions/users-permissions/server/services/providers-registry.js
This solves the problem of duplicated profiles.
For more details of the problem check here: https://github.com/orgs/dev-launchers/projects/29/views/1?pane=issue&itemId=85712147&issue=dev-launchers%7Cstrapiv4%7C240
Before create a profile we check this:
hasProfileAssociated ?
- no: create a profile with google displayName and PictureProfile
- yes: update displayName and PictureProfile (just if these are empty)
1. Loging in using google.
2. To test the scenarios is necessary to edit or delete the profile associated using the strapi admin content manager
=> Check if hasProfileAssociated when log in using Google

.github/workflows/test.yaml, commitlint.config.cjs, package-lock.json, package.json
This is a test to check if the failing gets triggered after a pull request. It specifically tests the commit message validation step (for example, "Test PR: Verifying that commit message linting fails when the message doesn't adhere to the conventional format of the semantic release")
=> test: add a linter test to ensure commit messages follow semantic release
